export const ETH_MAINNET = 1
export const AVALANCHE = 43114
export const AVALANCHE_FUJI = 43113
export const ARBITRUM = 42161
export const ARBITRUM_GOERLI = 421613
export const ARBITRUM_TESTNET = 421611

const SUPPORTED_CHAIN_IDS = [ARBITRUM, AVALANCHE]

SUPPORTED_CHAIN_IDS.push(ARBITRUM_TESTNET, AVALANCHE_FUJI)

export const GAS_PRICE_ADJUSTMENT_MAP = {
  [ARBITRUM]: '0',
  [AVALANCHE]: '3000000000' // 3 gwei
}
